# Generated by Django 5.2.3 on 2025-06-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='opt_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
