# Generated by Django 5.2.3 on 2025-06-21 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_user_opt_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='opt_code',
            new_name='otp_code',
        ),
    ]
