# Generated by Django 5.2.3 on 2025-06-25 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
