# Generated by Django 5.2.3 on 2025-06-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0007_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/'),
        ),
    ]
