# Generated by Django 5.2.3 on 2025-07-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0012_remove_userreport_user_product_main_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('black', 'Black'), ('white', 'White'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink'), ('brown', 'Brown'), ('gray', 'Gray'), ('navy', 'Navy'), ('gold', 'Gold'), ('silver', 'Silver'), ('rose_gold', 'Rose Gold'), ('custom', 'Custom Color')], max_length=20),
        ),
    ]
