# Generated by Django 5.2.3 on 2025-07-04 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0015_alter_productvariant_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together={('product', 'color', 'color_code')},
        ),
    ]
