# Generated by Django 5.2.3 on 2025-07-05 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0017_alter_productvariant_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariant',
            unique_together=set(),
        ),
    ]
