# Generated by Django 5.2.3 on 2025-07-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0021_address_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pro_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='profile_images/'),
        ),
    ]
