# Generated by Django 5.2.3 on 2025-07-16 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0024_order_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cancellation_reason',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='cancellation_reason',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='is_cancelled',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='is_returned',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='return_reason',
        ),
    ]
