# Generated by Django 5.2.3 on 2025-07-16 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0026_return'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Return',
        ),
    ]
