# Generated by Django 5.2.3 on 2025-07-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0028_returnrequest_wallet_wallettransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='update_at',
        ),
        migrations.AddField(
            model_name='wallet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
