# Generated by Django 5.2.3 on 2025-07-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0030_itemreturnrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='itemreturnrequest',
            name='requested_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
