# Generated by Django 5.2.3 on 2025-08-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0034_referraloffer_user_referral_code_user_referral_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('online', 'Online Payment'), ('wallet', 'Wallet Payment')], default='cod', max_length=20),
        ),
    ]
