# Generated by Django 5.2.3 on 2025-10-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0037_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
