from .common_imports import *
from .dashboard_views import *
from .user_views import *
from .category_views import *
from .referral_views import *
from .product_views import *
from .order_views import *
from .return_views import *
from .inventory_views import *
from .coupon_views import *
from .wallet_views import *
from .report_views import *
